version: '3.7'
services:
  postgres:

    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib
    environment:

      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345